
var orderValidator = new FormValidator();

      var sizes={33:"50 кг",34:"55 кг",39:"60 кг",42:"65 кг",45:"70 кг",50:"75 кг",53:"80 кг",56:"85 кг",60:"90 кг",63:"95 кг",67:"100 кг",71:"105 кг",74:"110 кг",79:"115 кг"},defaultSize=17;$.each(sizes,function(e,t){$("#sizer").append($("<option></option>").attr("value",e).attr("selected",e==defaultSize).text(t))});var times={7:"2 месяца",14:"1 месяц",30:"2 недели",60:"1 неделя"},defaultTime=14;function calc(){var e=$(".calc-form .inp1").val(),t=(i=$(".calc-form .inp2").val())-(l=$(".calc-form .inp3").val()),e=parseInt(e.replace(/\D+/g,"")),i=parseInt(i.replace(/\D+/g,"")),l=parseInt(l.replace(/\D+/g,""));console.log(t),0<e&&0<i&&0<l&&(115<=t?($(".calc-form .line1").attr("style","visibility: display;"),$(".calc-form .line2").attr("style","visibility: display;"),$(".calc-form .line1").html('<span class="green">Вы в прекрасной форме.</span>'),$(".calc-form .line2").html("Для её поддержания достаточно принимать Leptigen Meridian Diet один раз в неделю.")):104<=t&&t<=114?($(".calc-form .line1").attr("style","visibility: display;"),$(".calc-form .line2").attr("style","visibility: display;"),$(".calc-form .line1").html("У вас не более 10 кг лишнего веса"),$(".calc-form .line2").html("Достаточно пройти 2-недельный курс Leptigen Meridian Diet.")):90<=t&&t<=103?($(".calc-form .line1").attr("style","visibility: display;"),$(".calc-form .line2").attr("style","visibility: display;"),$(".calc-form .line1").html("У вас более 18 кг лишнего веса"),$(".calc-form .line2").html("Чтобы от него избавиться – рекомендуем пройти полный курс Leptigen Meridian Diet. Ожидаемая потеря веса в первый месяц – от 8 до 17 кг.")):t<=89&&($(".calc-form .line1").attr("style","visibility: display;"),$(".calc-form .line2").attr("style","visibility: display;"),$(".calc-form .line1").html("У вас крайняя стадия ожирения"),$(".calc-form .line2").html("Срочно пройдите расширенный курс Leptigen Meridian Diet (от 10 до 14 недель), а также добавьте физические нагрузки. За это время можно сбросить от 25 кг до 40 кг.")))}$.each(times,function(e,t){$("#timer").append($("<option></option>").attr("value",e).attr("selected",e==defaultTime).text(t))}),$("select").change(()=>{var e=100,t=parseInt($("#timer").val()),i=parseInt($("#sizer").val()),e=i+i*t*(7==t?.25/14:14==t?.2/14:30==t?.15/14:.1/14);$("#yourNewPenisYeah")
      .text(e.toFixed(2)+" кг")}),$("#timer").change(),
      $(document).ready(function(){$(".calc-form input").change(function(){calc()}),$(".calc-form input").keyup(function(){calc()})});var vibr,par=location.hash.slice(1).split("~"),parl=par.length;2<parl&&(isp=par[4].replace(/\+/g," ")),
      vibr="vibrate"in navigator?1:0;var count=1;$(function(){$(".try").click(function(){var e;count<2?($(this).attr("src","img/opened_box2.png"),$(this).addClass("empty"),count++,setTimeout(function(){document.getElementById("success02").className+=" animate",document.getElementById("successtip02").className+=" animateSuccessTip",document.getElementById("modal02").className+=" visible";document.getElementById("cntVal");document.querySelector(".sweet-overlay").style.display="block"},800)):document.getElementById("modal02").classList.contains("active")&&count<3&&!$(this).hasClass("empty")&&(count++,e=document.getElementById("discount"),$(this).replaceWith(e),$(e).addClass("show"),setTimeout(function(){resultWrapper.style.display="block"},1e3),setTimeout(function(){$("#boxes").slideUp(),$(".order_block").slideDown(),start_timer()},3500))})});var counter=1;$(document).ready(function(){$("#update").on("click",function(){document.getElementById("modal02").classList.add("active"),1==counter&&(counter++,$("#cntVal").html(function(e,t){return+t-1}))})});var resultWrapper=document.querySelector(".spin-result-wrapper"),wheel=document.querySelector(".wheel-img");function spin(){wheel.classList.contains("rotated")||(wheel.classList.add("super-rotation"),setTimeout(function(){resultWrapper.style.display="block"},8e3),setTimeout(function(){$(".spin-wrapper").slideUp(),$(".order_block").slideDown(),start_timer()},1e4),wheel.classList.add("rotated"))}var intr,time=600;function start_timer(){intr=setInterval(tick,1e3)}function tick(){--time;var e=Math.floor(time/60),t=time-60*e;0==e&&0==t&&clearInterval(intr),t=10<=t?t:"0"+t,$("#min").html("0"+e),$("#sec").html(t)}function hidemodal01(){0<vibr&&navigator.vibrate(70);document.getElementById("modal01").classList.remove("visible"),document.querySelector(".sweet-overlay").style.display="none"}function hidemodal02(){0<vibr&&navigator.vibrate(70);document.getElementById("modal02").classList.remove("visible"),document.querySelector(".sweet-overlay").style.display="none"}$(".ord_button").on("click",function(){$(".screenLock .msg .close").trigger("click")}),$(document).ready(function(){$(".close-popup").on("click",function(){resultWrapper.style.display="none"})}),$(document).ready(function(){$(".pop-up-button").on("click",function(){resultWrapper.style.display="none"})}),$("a").addClass("to_form"),$(".to_form").on("touchend, click",function(e){e.preventDefault(),$("body,html").animate({scrollTop:$(".zakaz").offset().top},400)});


(app.jq);














